//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// Rotation_yap_res.rc

#define IDC_STATIC                          -1

#define IDD_CONFIG                          100

#define IDS_ROTATION_NONE                   100
#define IDS_ROTATION_90                     101
#define IDS_ROTATION_180                    102
#define IDS_ROTATION_270                    103
#define IDS_FLIPH                           104
#define IDS_FLIPV                           105

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
