//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// Clock_yap_res.rc

#define IDD_CONFIG                          100

#define IDS_LEFT                            100
#define IDS_CENTER                          101
#define IDS_RIGHT                           102
#define IDS_TOP                             103
#define IDS_MIDDLE                          104
#define IDS_BOTTOM                          105

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
